export enum TypeAdmin {
  RESPONSABLE_ETABLISSEMENT = 'RESPONSABLE_ETABLISSEMENT',
  RESPONSABLE_FORMATION = 'RESPONSABLE_FORMATION',
  ASSISTANT_VIE_SCOLAIRE = 'ASSISTANT_VIE_SCOLAIRE',
  ASSISTANT_ADMINISTRATIF = 'ASSISTANT_ADMINISTRATIF'
}
